name: Failure Notification Test

on:
  pull_request:

jobs:
  notify_failure:
    # if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: SonicGarden/world-notify-action@v1
        with:
          token: ${{ secrets.WORLD_NOTIFY_APP_TOKEN }}
          groupId: ${{ secrets.WORLD_NOTIFY_APP_GROUP_ID }}
          content: |
            ${{ github.event.repository.name }} の ${{ github.workflow }} の通知テストです！

            詳細はこちら
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
